### ISSUE TITLE
Can't open 'deps-deploy.deps-deploy' error

### ISSUE THREAD

**Issue by arichiardi** [slipset/deps-deploy#10]
Hi :smile: 

So now that I have the gpg setup going, with the following:

```
clojure -A:deploy -m deps-deploy.deps-deploy deploy unbroken-promises.jar true
```

I receive:

```
Exception in thread "main" java.lang.Exception: gpg: can't open 'deps-deploy.deps-deploy': No such file or directory
gpg: signing failed: No such file or directory

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:305)
	at deps_deploy.gpg$sign_BANG_.invokeStatic(gpg.clj:52)
	at deps_deploy.gpg$sign_BANG_.invoke(gpg.clj:45)
	at deps_deploy.deps_deploy$sign_BANG_.invokeStatic(deps_deploy.clj:53)
	at deps_deploy.deps_deploy$sign_BANG_.invoke(deps_deploy.clj:51)
	at deps_deploy.deps_deploy$all_artifacts.invokeStatic(deps_deploy.clj:62)
	at deps_deploy.deps_deploy$all_artifacts.invoke(deps_deploy.clj:60)
	at deps_deploy.deps_deploy$_main.invokeStatic(deps_deploy.clj:87)
	at deps_deploy.deps_deploy$_main.doInvoke(deps_deploy.clj:83)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by slipset** [comment]
I'd need to see your `:deploy` alias, but my suspicion would be that you should run something like:
```
$ clojure -A:deploy
```
and have the rest of the stuff handled by your `:deploy` alias?

**Comment by arichiardi** [comment]
Yeah it seems I thought I could pass additional options but the `-m` does not like it.

After fixing it I receive:

```
Deploying unbroken-promises/unbroken-promises-0.1.1 to clojars as nil
Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: {:artifact-map {[:extension "pom" :classifier nil] "pom.xml", [:extension "jar" :classifier nil] "unbroken-promises.jar", [:extension "xml.asc" :classifier nil] "pom.xml.asc", [:extension "jar.asc" :classifier nil] "unbroken-promises.jar.asc"}, :repository {"clojars" {:url "https://clojars.org/repo", :username nil, :password nil}}, :coordinates [unbroken-promises/unbroken-promises "0.1.1"]}
at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
	at cemerick.pomegranate.aether$deploy.invokeStatic(aether.clj:391)
	at cemerick.pomegranate.aether$deploy.doInvoke(aether.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at deps_deploy.deps_deploy$eval1648$fn__1650.invoke(deps_deploy.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at deps_deploy.deps_deploy$_main.invokeStatic(deps_deploy.clj:85)
	at deps_deploy.deps_deploy$_main.doInvoke(deps_deploy.clj:83)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

Sorry for the church I might be having a slow day here as well :smile:

**Comment by slipset** [comment]
hmm, have you run 
```
$ clj -Spom
```
before deploying?

**Comment by arichiardi** [comment]
I think I did, the project is here btw: https://github.com/arichiardi/unbroken-promises

**Comment by slipset** [comment]
I reproduced it. Hang on.

**Comment by slipset** [comment]
you might have forgot set your Clojars username/passwd?
```
env CLOJARS_USERNAME=username CLOJARS_PASSWORD=password clj -a:deploy
```

**Comment by arichiardi** [comment]
oh ok, let me try that
